# Regenerates external/skia-c-api/libSkiaSharp.def from the exports of the pinned
# libSkiaSharp.dll.
#
# The SkiaSharp NuGet package ships a DLL and a PDB and no import library, so there is nothing
# to link against until this has run and lib.exe has turned the result into a .lib.
#
# Run this after changing $SkiaSharpVersion, and then re-run the pixel probe: a .def produced
# from a different DLL will still link, because an import library resolves whatever names the
# .def lists. Only reading pixels back proves the three pieces agree.

param(
    [string]$SkiaSharpVersion = "3.119.4",
    [string]$Rid = "win-x64"
)

$ErrorActionPreference = "Stop"

$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$root = Join-Path (Split-Path -Parent $here) "external\skia-c-api"

$dll = Join-Path $env:USERPROFILE ".nuget\packages\skiasharp.nativeassets.win32\$SkiaSharpVersion\runtimes\$Rid\native\libSkiaSharp.dll"
if (-not (Test-Path -LiteralPath $dll)) {
    throw "libSkiaSharp.dll not found at $dll. Restore a project that references SkiaSharp.NativeAssets.Win32 $SkiaSharpVersion first."
}

$dumpbin = Get-ChildItem "C:\Program Files*\Microsoft Visual Studio\*\*\VC\Tools\MSVC\*\bin\Hostx64\x64\dumpbin.exe" -ErrorAction SilentlyContinue |
           Sort-Object FullName -Descending | Select-Object -First 1
if (-not $dumpbin) { throw "dumpbin.exe not found. It ships with the Visual Studio C++ tools." }

$out = & $dumpbin.FullName /EXPORTS $dll | Out-String

# Ordinal, hint, RVA, name. Matching the name column alone would also pick up the section
# headers dumpbin prints around the table.
$names = [regex]::Matches($out, '(?m)^\s+\d+\s+[0-9A-F]+\s+[0-9A-F]{8}\s+(\S+)') |
         ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique

if ($names.Count -lt 500) {
    throw "Only $($names.Count) exports parsed out of $dll, which is too few to be the whole C API. The dumpbin output format may have changed; fix the parse rather than shipping a partial .def."
}

$lines = @(
    "; Import library definition for libSkiaSharp.dll."
    ";"
    "; Generated by tools/regen-skia-def.ps1 from SkiaSharp.NativeAssets.Win32 $SkiaSharpVersion ($Rid)."
    "; That package ships a DLL and a PDB and no import library, so one is built from this file."
    ";"
    "; Do not hand-edit: a name here that the DLL does not export still links, and fails at load."
    "LIBRARY libSkiaSharp"
    "EXPORTS"
) + ($names | ForEach-Object { "    $_" })

$defPath = Join-Path $root "libSkiaSharp.def"
Set-Content -LiteralPath $defPath -Value ($lines -join "`r`n") -Encoding ASCII

"wrote $defPath with $($names.Count) exports"
"now rebuild, then run the pixel probe - a clean link is not evidence"
